// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	model "github.com/sentrionic/valkyrie/model"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// FriendService is an autogenerated mock type for the FriendService type
type FriendService struct {
	mock.Mock
}

// DeleteRequest provides a mock function with given fields: memberId, userId
func (_m *FriendService) DeleteRequest(memberId string, userId string) error {
	ret := _m.Called(memberId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(memberId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFriends provides a mock function with given fields: id
func (_m *FriendService) GetFriends(id string) (*[]model.Friend, error) {
	ret := _m.Called(id)

	var r0 *[]model.Friend
	if rf, ok := ret.Get(0).(func(string) *[]model.Friend); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.Friend)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemberById provides a mock function with given fields: id
func (_m *FriendService) GetMemberById(id string) (*model.User, error) {
	ret := _m.Called(id)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequests provides a mock function with given fields: id
func (_m *FriendService) GetRequests(id string) (*[]model.FriendRequest, error) {
	ret := _m.Called(id)

	var r0 *[]model.FriendRequest
	if rf, ok := ret.Get(0).(func(string) *[]model.FriendRequest); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.FriendRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFriend provides a mock function with given fields: memberId, userId
func (_m *FriendService) RemoveFriend(memberId string, userId string) error {
	ret := _m.Called(memberId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(memberId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRequests provides a mock function with given fields: user
func (_m *FriendService) SaveRequests(user *model.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFriendService creates a new instance of FriendService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewFriendService(t testing.TB) *FriendService {
	mock := &FriendService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
