// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MailRepository is an autogenerated mock type for the MailRepository type
type MailRepository struct {
	mock.Mock
}

// SendResetMail provides a mock function with given fields: email, html
func (_m *MailRepository) SendResetMail(email string, html string) error {
	ret := _m.Called(email, html)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, html)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailRepository creates a new instance of MailRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMailRepository(t testing.TB) *MailRepository {
	mock := &MailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
