// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MailRepository is an autogenerated mock type for the MailRepository type
type MailRepository struct {
	mock.Mock
}

// SendResetMail provides a mock function with given fields: email, html
func (_m *MailRepository) SendResetMail(email string, html string) error {
	ret := _m.Called(email, html)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, html)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
