// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	model "github.com/sentrionic/valkyrie/model"
	mock "github.com/stretchr/testify/mock"
)

// SocketService is an autogenerated mock type for the SocketService type
type SocketService struct {
	mock.Mock
}

// EmitAddFriend provides a mock function with given fields: user, member
func (_m *SocketService) EmitAddFriend(user *model.User, member *model.User) {
	_m.Called(user, member)
}

// EmitAddFriendRequest provides a mock function with given fields: room, request
func (_m *SocketService) EmitAddFriendRequest(room string, request *model.FriendRequest) {
	_m.Called(room, request)
}

// EmitAddMember provides a mock function with given fields: room, member
func (_m *SocketService) EmitAddMember(room string, member *model.User) {
	_m.Called(room, member)
}

// EmitDeleteChannel provides a mock function with given fields: channel
func (_m *SocketService) EmitDeleteChannel(channel *model.Channel) {
	_m.Called(channel)
}

// EmitDeleteGuild provides a mock function with given fields: guildId, members
func (_m *SocketService) EmitDeleteGuild(guildId string, members []string) {
	_m.Called(guildId, members)
}

// EmitDeleteMessage provides a mock function with given fields: room, messageId
func (_m *SocketService) EmitDeleteMessage(room string, messageId string) {
	_m.Called(room, messageId)
}

// EmitEditChannel provides a mock function with given fields: room, channel
func (_m *SocketService) EmitEditChannel(room string, channel *model.ChannelResponse) {
	_m.Called(room, channel)
}

// EmitEditGuild provides a mock function with given fields: guild
func (_m *SocketService) EmitEditGuild(guild *model.Guild) {
	_m.Called(guild)
}

// EmitEditMessage provides a mock function with given fields: room, message
func (_m *SocketService) EmitEditMessage(room string, message *model.MessageResponse) {
	_m.Called(room, message)
}

// EmitNewChannel provides a mock function with given fields: room, channel
func (_m *SocketService) EmitNewChannel(room string, channel *model.ChannelResponse) {
	_m.Called(room, channel)
}

// EmitNewDMNotification provides a mock function with given fields: channelId, user
func (_m *SocketService) EmitNewDMNotification(channelId string, user *model.User) {
	_m.Called(channelId, user)
}

// EmitNewMessage provides a mock function with given fields: room, message
func (_m *SocketService) EmitNewMessage(room string, message *model.MessageResponse) {
	_m.Called(room, message)
}

// EmitNewNotification provides a mock function with given fields: guildId, channelId
func (_m *SocketService) EmitNewNotification(guildId string, channelId string) {
	_m.Called(guildId, channelId)
}

// EmitNewPrivateChannel provides a mock function with given fields: members, channel
func (_m *SocketService) EmitNewPrivateChannel(members []string, channel *model.ChannelResponse) {
	_m.Called(members, channel)
}

// EmitRemoveFriend provides a mock function with given fields: userId, memberId
func (_m *SocketService) EmitRemoveFriend(userId string, memberId string) {
	_m.Called(userId, memberId)
}

// EmitRemoveFromGuild provides a mock function with given fields: memberId, guildId
func (_m *SocketService) EmitRemoveFromGuild(memberId string, guildId string) {
	_m.Called(memberId, guildId)
}

// EmitRemoveMember provides a mock function with given fields: room, memberId
func (_m *SocketService) EmitRemoveMember(room string, memberId string) {
	_m.Called(room, memberId)
}

// EmitSendRequest provides a mock function with given fields: room
func (_m *SocketService) EmitSendRequest(room string) {
	_m.Called(room)
}
